# Quantum's Secrets Management - External Secrets Operator Configuration
# Secure secrets management with AWS Secrets Manager integration

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: astral-planner-production
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: astral-planner
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: astral-planner-staging
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: astral-planner
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
# External Secret for Production Application Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: astral-planner-secrets
  namespace: astral-planner-production
  labels:
    app.kubernetes.io/name: astral-planner
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: astral-planner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: astral-planner-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        DATABASE_URL: "{{ .database_url }}"
        REDIS_URL: "{{ .redis_url }}"
        JWT_SECRET: "{{ .jwt_secret }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        STACK_SECRET_SERVER_KEY: "{{ .stack_secret_key }}"
        STACK_PUBLISHABLE_CLIENT_KEY: "{{ .stack_publishable_key }}"
        AI_API_KEY: "{{ .ai_api_key }}"
        PUSHER_APP_ID: "{{ .pusher_app_id }}"
        NEXT_PUBLIC_PUSHER_KEY: "{{ .pusher_key }}"
        PUSHER_SECRET: "{{ .pusher_secret }}"
        GOOGLE_CLIENT_ID: "{{ .google_client_id }}"
        GOOGLE_CLIENT_SECRET: "{{ .google_client_secret }}"
        STRIPE_PUBLISHABLE_KEY: "{{ .stripe_publishable_key }}"
        STRIPE_SECRET_KEY: "{{ .stripe_secret_key }}"
        STRIPE_WEBHOOK_SECRET: "{{ .stripe_webhook_secret }}"
        EMAIL_API_KEY: "{{ .email_api_key }}"
        SENTRY_DSN: "{{ .sentry_dsn }}"
        SENTRY_AUTH_TOKEN: "{{ .sentry_auth_token }}"
        ANALYTICS_API_KEY: "{{ .analytics_api_key }}"
  data:
  - secretKey: database_url
    remoteRef:
      key: astral-planner-production-app-secrets
      property: database_url
  - secretKey: redis_url
    remoteRef:
      key: astral-planner-production-app-secrets
      property: redis_url
  - secretKey: jwt_secret
    remoteRef:
      key: astral-planner-production-app-secrets
      property: jwt_secret
  - secretKey: encryption_key
    remoteRef:
      key: astral-planner-production-app-secrets
      property: encryption_key
  - secretKey: stack_secret_key
    remoteRef:
      key: astral-planner-production-app-secrets
      property: stack_secret_key
  - secretKey: stack_publishable_key
    remoteRef:
      key: astral-planner-production-app-secrets
      property: stack_publishable_key
  - secretKey: ai_api_key
    remoteRef:
      key: astral-planner-production-app-secrets
      property: ai_api_key
  - secretKey: pusher_app_id
    remoteRef:
      key: astral-planner-production-app-secrets
      property: pusher_app_id
  - secretKey: pusher_key
    remoteRef:
      key: astral-planner-production-app-secrets
      property: pusher_key
  - secretKey: pusher_secret
    remoteRef:
      key: astral-planner-production-app-secrets
      property: pusher_secret
  - secretKey: google_client_id
    remoteRef:
      key: astral-planner-production-app-secrets
      property: google_client_id
  - secretKey: google_client_secret
    remoteRef:
      key: astral-planner-production-app-secrets
      property: google_client_secret
  - secretKey: stripe_publishable_key
    remoteRef:
      key: astral-planner-production-app-secrets
      property: stripe_publishable_key
  - secretKey: stripe_secret_key
    remoteRef:
      key: astral-planner-production-app-secrets
      property: stripe_secret_key
  - secretKey: stripe_webhook_secret
    remoteRef:
      key: astral-planner-production-app-secrets
      property: stripe_webhook_secret
  - secretKey: email_api_key
    remoteRef:
      key: astral-planner-production-app-secrets
      property: email_api_key
  - secretKey: sentry_dsn
    remoteRef:
      key: astral-planner-production-app-secrets
      property: sentry_dsn
  - secretKey: sentry_auth_token
    remoteRef:
      key: astral-planner-production-app-secrets
      property: sentry_auth_token
  - secretKey: analytics_api_key
    remoteRef:
      key: astral-planner-production-app-secrets
      property: analytics_api_key
---
# External Secret for Staging Application Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: astral-planner-secrets
  namespace: astral-planner-staging
  labels:
    app.kubernetes.io/name: astral-planner
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: astral-planner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: astral-planner-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        DATABASE_URL: "{{ .database_url }}"
        REDIS_URL: "{{ .redis_url }}"
        JWT_SECRET: "{{ .jwt_secret }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        STACK_SECRET_SERVER_KEY: "{{ .stack_secret_key }}"
        STACK_PUBLISHABLE_CLIENT_KEY: "{{ .stack_publishable_key }}"
        AI_API_KEY: "{{ .ai_api_key }}"
        PUSHER_APP_ID: "{{ .pusher_app_id }}"
        NEXT_PUBLIC_PUSHER_KEY: "{{ .pusher_key }}"
        PUSHER_SECRET: "{{ .pusher_secret }}"
        GOOGLE_CLIENT_ID: "{{ .google_client_id }}"
        GOOGLE_CLIENT_SECRET: "{{ .google_client_secret }}"
        STRIPE_PUBLISHABLE_KEY: "{{ .stripe_publishable_key }}"
        STRIPE_SECRET_KEY: "{{ .stripe_secret_key }}"
        STRIPE_WEBHOOK_SECRET: "{{ .stripe_webhook_secret }}"
        EMAIL_API_KEY: "{{ .email_api_key }}"
        SENTRY_DSN: "{{ .sentry_dsn }}"
        SENTRY_AUTH_TOKEN: "{{ .sentry_auth_token }}"
        ANALYTICS_API_KEY: "{{ .analytics_api_key }}"
  data:
  - secretKey: database_url
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: database_url
  - secretKey: redis_url
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: redis_url
  - secretKey: jwt_secret
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: jwt_secret
  - secretKey: encryption_key
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: encryption_key
  - secretKey: stack_secret_key
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: stack_secret_key
  - secretKey: stack_publishable_key
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: stack_publishable_key
  - secretKey: ai_api_key
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: ai_api_key
  - secretKey: pusher_app_id
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: pusher_app_id
  - secretKey: pusher_key
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: pusher_key
  - secretKey: pusher_secret
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: pusher_secret
  - secretKey: google_client_id
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: google_client_id
  - secretKey: google_client_secret
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: google_client_secret
  - secretKey: stripe_publishable_key
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: stripe_publishable_key
  - secretKey: stripe_secret_key
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: stripe_secret_key
  - secretKey: stripe_webhook_secret
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: stripe_webhook_secret
  - secretKey: email_api_key
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: email_api_key
  - secretKey: sentry_dsn
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: sentry_dsn
  - secretKey: sentry_auth_token
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: sentry_auth_token
  - secretKey: analytics_api_key
    remoteRef:
      key: astral-planner-staging-app-secrets
      property: analytics_api_key
---
# Service Account for External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: astral-planner-production
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/astral-planner-production-external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: astral-planner-staging
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/astral-planner-staging-external-secrets